// Code generated by gintool.

package main

import (
	"github.com/gin-gonic/gin"
	"talkapp/biz/handler"
)

func main() {
	router := gin.Default()
	router.GET("/ping", handler.Ping)
	router.POST("/api/v1/:method", handler.CompareHandler)
	router.Run("0.0.0.0:8080")
}
