// Code generated by gintool. DO NOT EDIT.

package main

import (
	"code.byted.org/gin/ginex"

	"code.byted.org/zhangbofei.5675/demo/biz/handler"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *ginex.Engine) {
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
}
